name: Print Mesage

on:
    push:
        branches:
            - 'main'

jobs:
    print-message:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: echo "new push detected on main branch"